### ISSUE TITLE
Plugin can't read '<' character

### ISSUE THREAD

**Issue by mkrdip** [kasparsd/code-prettify#12]
If you write 

```
<?php 

/* some codes */

?>
```

The Plugin won't show the code block.

But this will work

```
&lt;?php 

/* some codes */

?>
```

So, please allow **<** as like it's html entity `&lt;`

I've checked that at my [blog](http://mkrdip.me) with Twenty Fifteen theme.

**Comment by kasparsd** [comment]
`<` and `>` should always be escaped in HTML, even inside the `<pre>`. See this http://stackoverflow.com/a/13010144

**Comment by kasparsd** [comment]
This is how it looks if escaped properly:

![prettify-pre-escaping](https://cloud.githubusercontent.com/assets/169055/9282308/2853410e-42d4-11e5-89f6-100aedf875c9.png)
