### ISSUE TITLE
Plugin seems to be replacing the font

### ISSUE THREAD

**Issue by shreedhanvaidya** [kasparsd/code-prettify#16]
The plugin is replacing the font on pre and code blocks.

Example URL: http://excelcheat.net/remove-trailing-slash/ (plugin is active at the moment)

Preview with plugin deactivated:
![image](https://cloud.githubusercontent.com/assets/15247031/17651343/2b72a3f8-625d-11e6-999b-d47e3634bd18.png)

Preview with plugin active:
![image](https://cloud.githubusercontent.com/assets/15247031/17651346/3626fdf8-625d-11e6-8eee-efda667dbb94.png)

Might be an issue with the theme I'm using, just wanted to flag!

**Comment by kasparsd** [comment]
@shreedhanvaidya Are those two screenshots supposed to have the same content?

I'm seeing the following font rule for the `pre` block in the `style.css` of your theme (line 2952):

```
code,
kbd,
pre,
samp {
    font-family: Menlo, Monaco, Consolas, "Courier New", monospace;
}
```

I'm not sure why it would be different with this plugin deactivated.

**Comment by kasparsd** [comment]
@shreedhanvaidya So your theme specifies a different font for `span` elements:

```
span {
  font-family: 'Noto sans', sans-serif;
}
```

which are added by the Prettify library to parts of code to specify/target the syntax type.

**Comment by shreedhanvaidya** [comment]
Thanks for your help! I feel pretty stupid! I'll remove that now.
