### ISSUE TITLE
Code snippets displays wrong on narrower screens

### ISSUE THREAD

**Issue by oyvindmal** [kasparsd/code-prettify#19]
Displayed on a narrow screen (simulated with chrome)
![image](https://cloud.githubusercontent.com/assets/603382/23850878/9b11bb66-07e1-11e7-97e2-1fb3cc3066a3.png)

How it should have looked
![image](https://cloud.githubusercontent.com/assets/603382/23850894/a85c43e0-07e1-11e7-9309-fcc53a5639ef.png)

**Comment by kasparsd** [comment]
@oyvindmal That looks like a CSS issue with the `pre` formatting. Have you tried setting:

```
pre { overflow-x: scroll; }
```

**Comment by oyvindmal** [comment]
Doesnt seem to do anything except add scrollbars 
![image](https://cloud.githubusercontent.com/assets/603382/23851128/996d8ae6-07e2-11e7-9af2-fec356476e5a.png)

**Comment by kasparsd** [comment]
@oyvindmal Unfortunately, I can't really you debug this without having access to the actual URL.

**Comment by oyvindmal** [comment]
I can email you or DM you the link provided that its not spread

**Comment by kasparsd** [comment]
@oyvindmal Maybe the CSS style for the `pre` element has `white-space: pre-wrap;` which enforces the line breaks?

Secondly, changing `pre { overflow-x: scroll; }` to `pre { overflow-x: auto; }` should get rid of the scrollbars unless they're actually needed.

**Comment by oyvindmal** [comment]
It seems like it flips the curly-braces aswell. I will investigate further later today and update
