### ISSUE TITLE
Not support for xml format

### ISSUE THREAD

**Issue by Danushka96** [kasparsd/code-prettify#23]
This Snippet currently not support for xml code format

**Comment by jamesliu668** [comment]
Is there a plan to support xml code?

**Comment by kasparsd** [comment]
The Prettify JS library used by this plugin does support XML per [the docs](https://github.com/googlearchive/code-prettify/tree/e006587b4a893f0281e9dc9a53001c7ed584d4e7#for-which-languages-does-it-work):

> The comments in prettify.js are authoritative but the lexer should work on a number of languages including C and friends, Java, Python, Bash, SQL, HTML, XML, CSS, JavaScript, Makefile, and Rust.

Here is an example of [a post on my blog](https://kaspars.net/blog/apple-podcasts-subscriptions) with some XML that has been highlighted as expected.
