### ISSUE TITLE
Not working with WP 5.0

### ISSUE THREAD

**Issue by khoipro** [kasparsd/code-prettify#24]
Version: WordPress 5.0.2

Errors:

```
SyntaxError: unexpected token: ')'
```

Using with Jetpack plugin.

Live site: https://wphub.vn/tat-gutenberg-wordpress/

**Comment by kasparsd** [comment]
Thanks for reporting the issue @khoipro! I'm using the plugin with WordPress 5.0 on my own blog (see [this recent post made with Gutenberg](https://kaspars.net/blog/wordpress/laravel-homestead-wordpress)) without any errors or warnings.

Your site [appears to be running some kind of minification plugin](https://wphub.vn/min/2252e.js) which is probably causing the issue.
