### ISSUE TITLE
Triggered a fatal error.

### ISSUE THREAD

**Issue by sulavMalla** [kasparsd/code-prettify#25]
After installing, I get the following error while trying to activate it.

Plugin could not be activated because it triggered a fatal error.
Parse error: syntax error, unexpected '[' in /var/www/html/blog/wp-content/plugins/code-prettify/code-prettify.php on line 28

**Comment by kasparsd** [comment]
Thanks for reporting the issue @sulavMalla!

This appears to be a problem with an older version of PHP which doesn't support the shorthand syntax `[]` for arrays. This is a feature introduced [in PHP 5.4](http://php.net/manual/en/migration54.new-features.php) six years ago.

If possible, I would strongly recommend to upgrade your host to a newer version of PHP. This is usually possible in the admin panel of your hosting provider.

**Comment by kasparsd** [comment]
This has been fixed in version 1.4.2. Thanks again @sulavMalla!

**Comment by sulavMalla** [comment]
Wow! Thank you for the quick fix @kasparsd.
