### ISSUE TITLE
Not working properly with Wordpress blocks (Gutenberg)

### ISSUE THREAD

**Issue by collimarco** [kasparsd/code-prettify#28]
The plugin doesn't work as expected with the latest versions of Wordpress.

It works with posts created in the past without blocks ([example](https://blog.pushpad.xyz/2018/11/how-to-send-a-notification-only-to-a-random-subset-of-users/
))

It doesn't work with posts created with blocks ([example](https://blog.pushpad.xyz/2019/03/adding-a-service-worker-to-wordpress/))

Basically **it treats code blocks as inline code, instead of code blocks**. I think this is a bug.

**Comment by kasparsd** [comment]
Thanks for reporting the issue @collimarco!

I'm using the plugin on my own blog ([see this post](https://kaspars.net/blog/laravel-homestead-wordpress)) with blocks and it is working as expected as long as I use the "code" block.

Your theme is adding the following styles for `<code>` elements:

```css
code {
	background-color: #d1d1d1;
	padding: 0.125em 0.25em;
}
```

which makes the grey background. You can probably override it with the [customizer styles](https://www.wpbeginner.com/plugins/how-to-easily-add-custom-css-to-your-wordpress-site/).
