### ISSUE TITLE
Missing C#

### ISSUE THREAD

**Issue by pediRAM** [kasparsd/code-prettify#34]
Hello and thank you for your efforts!
I am missing colorization for C# (everything is black when using class="language-cs").
I could abuse class="language-java" but then in the top-right-corner there would be written/standing "Java" (which would not be correct).
Is there any chance to extend the syntaxhighlightnings with C# one?
Please let me know if I can help you with keywords, regular-expressions aso.
Kindly regards.

**Comment by kasparsd** [comment]
This plugin relies on the Code Prettify library from Google https://github.com/googlearchive/code-prettify which has been archived and isn't maintained anymore.

It appears that CSHARP is supported out of the box https://github.com/googlearchive/code-prettify/blob/e006587b4a893f0281e9dc9a53001c7ed584d4e7/src/prettify.js#L189-L194
