### ISSUE TITLE
Minit plugin compatibility

### ISSUE THREAD

**Issue by ryanhellyer** [kasparsd/code-prettify#8]
I'm having difficulties making this work with the Minit plugin.

The Minit plugin is stripping out the variable code_prettify_settings, which then prevents it from working. Do you have any ideas how to work around this problem?

**Comment by kasparsd** [comment]
It seems to work just fine on [this blog post, for example](http://kaspars.net/blog/wordpress/custom-page-template-front-page). Are you running the latest version of Minit?

**Comment by ryanhellyer** [comment]
Yep, latest version of both Minit and Code Prettify.

**Comment by ryanhellyer** [comment]
I tested it on a fresh local install, and it also works from me there :/

For some reason it does not work at https://geek.hellyer.kiwi/ but I'll have a poke around and see if I can work out what is breaking it.

**Comment by ryanhellyer** [comment]
I have no idea what is causing this problem. I can't replicate it on a fresh local site, only on my live site. I tried replicating my live site on the same server and saw the same problem. I then turned off all other plugins, switched to the TwentyEleven theme, and still saw the same issue.

I've given up and used the Minqueue plugin in the mean time :/
