### ISSUE TITLE
Suggestions regarding to the Readme.txt

### ISSUE THREAD

**Issue by johnyluyte** [kasparsd/code-prettify#9]
I have some suggestions regarding to the Readme.txt.

1. There is a plugin in Wordpress's plugin repository that has the same name as yours.
Please see: [https://wordpress.org/plugins/code-prettify/](https://wordpress.org/plugins/code-prettify/). Maybe you can mention it in the readme.txt to clarify that these are two different plugins. 

2. I think #6 should be listed in Frequently Asked Questions since people (like me) may wonder why they could not find this wonderful plugin in Wordpress's plugin repository.

I have tried several famous code highlighter for Wordpress. And I have to say that this is the best one in my opinion. Good job & thanks you.

**Comment by Willem-Siebe** [comment]
Agree, it's the best!

**Comment by kasparsd** [comment]
@johnyluyte @Willem-Siebe This plugin is now on WordPress.org repository at that same URL https://wordpress.org/plugins/code-prettify/
